# Generated by Django 5.0.2 on 2024-03-23 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_comment_comment_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='home.post'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
