# Generated by Django 5.0.2 on 2024-03-29 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_post_parent_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='tweet',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
    ]
