# Generated by Django 5.0.2 on 2024-03-31 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_comment_tweet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-created',)},
        ),
    ]
