# Generated by Django 5.0.2 on 2024-04-09 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_remove_like_likes_like_created_like_post_like_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/posts', verbose_name='تصویر'),
        ),
    ]
